[program:gurkynet-scheduler]
command=/bin/bash -c "while true; do php /var/www/GurkyNet/laravel/artisan schedule:run --verbose --no-interaction; sleep 60; done"
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/GurkyNet/laravel/storage/logs/scheduler.log
stopwaitsecs=60
